#!/bin/bash

if [ $# -ne 1 ];
then CD="."
else CD=$1
fi

echo "Current Dir: $CD"

ARCH32=x86
ARCH64=x64

BIN=$CD/bin
BIN32=$BIN/$ARCH32
BIN64=$BIN/$ARCH64

OBJ=$CD/obj
OBJ32=$OBJ/$ARCH32
OBJ64=$OBJ/$ARCH64

SRC=$CD/src
INC=$CD/inc

function create_dir
{
	echo Creating "$1" dir
	mkdir -p "$1"	
	chmod +rwx "$1"
}

create_dir "$SRC"
create_dir "$INC"
create_dir "$OBJ32"
create_dir "$OBJ64"
create_dir "$BIN32"
create_dir "$BIN64"

mkmkfl