#!/bin/bash

ARCH32=x86
ARCH64=x64

BIN=./bin
BIN32=$BIN/$ARCH32
BIN64=$BIN/$ARCH64

OBJ=./obj
OBJ32=$OBJ/$ARCH32
OBJ64=$OBJ/$ARCH64

SRC=./src
INC=./inc

echo Creating source dir
mkdir -p $SRC
echo Creating include dir
mkdir -p $INC
echo Creating object32 dir
mkdir -p $OBJ32
echo Creating object64 dir
mkdir -p $OBJ64
echo Creating binary32 dir
mkdir -p $BIN32
echo Creating binary64 dir
mkdir -p $BIN64

echo Creating Makefile
touch ./Makefile

echo Changing permissions for bin dir
chmod +rwx $BIN
echo Changing permissions for bin32 dir
chmod +rwx $BIN32
echo Changing permissions for bin64 dir
chmod +rwx $BIN64

echo Changing permissions for obj dir
chmod +rwx $OBJ
echo Changing permissions for obj32 dir
chmod +rwx $OBJ32
echo Changing permissions for obj64 dir
chmod +rwx $OBJ64

echo Changing permissions for inc dir
chmod +rwx $INC
echo Changing permissions for src dir
chmod +rwx $SRC

echo Creating Makefile
touch ./Makefile
chmod +rwx ./Makefile

read -re -i "app" -p "Choose Target Name: " TARGET

echo "INC_DIR=$INC" > ./Makefile
echo "SRC_DIR=$SRC" >> ./Makefile
echo "BIN_DIR=$BIN" >> ./Makefile
echo 'BIN_DIR_X86=$(BIN_DIR)/$ARCH32' >> ./Makefile
echo 'BIN_DIR_X64=$(BIN_DIR)/$ARCH64' >> ./Makefile
echo "OBJ_DIR=$OBJ" >> ./Makefile
echo 'OBJ_DIR_X86=$(OBJ_DIR)/$ARCH32' >> ./Makefile
echo 'OBJ_DIR_X64=$(OBJ_DIR)/$ARCH64' >> ./Makefile
echo "" >> ./Makefile
echo "TARGET_NAME=$TARGET" >> ./Makefile
echo 'TARGET_DIR_X86=$(BIN_DIR_X86)' >> ./Makefile
echo 'TARGET_PATH_X86=$(TARGET_DIR_X86)/$(TARGET_NAME)' >> ./Makefile
echo 'TARGET_DIR_X64=$(BIN_DIR_X64)' >> ./Makefile
echo 'TARGET_PATH_X64=$(TARGET_DIR_X64)/$(TARGET_NAME)' >> ./Makefile
echo "" >> ./Makefile

echo "clean_x86:" >> ./Makefile
echo '	rm $(OBJ_DIR_X86)/*.o' >> ./Makefile

echo "mrproper_x86:" >> ./Makefile
echo '	rm $(TARGET_PATH_X86)' >> ./Makefile

echo "clean_x64:" >> ./Makefile
echo '	rm $(OBJ_DIR_X64)/*.o' >> ./Makefile

echo "mrproper_x64:" >> ./Makefile
echo '	rm $(TARGET_PATH_X64)' >> ./Makefile

echo ".PHONY: mrproper_x86 mrproper_64 clean_x86 clean_x64" >> ./Makefile
echo "" >> ./Makefile
echo "all_x86:" >> ./Makefile
echo "all_x64:" >> ./Makefile
echo "all: all_x86 all_x64" >> ./Makefile
